### ISSUE TITLE
有实物效果演示吗

### ISSUE THREAD

**Issue by kowyo** [MaxwellJay256/Bike-Computer#24]

**Comment by MaxwellJay256** [comment]
过两天会上传照片或者演示视频到 README 的😆

但是不要对外观有太高期待😂

**Comment by MaxwellJay256** [comment]
上传了唯一一张保留下来的照片： 7286063ef43e7661b2bbd34a4f5e215c13c6c241

结题答辩前用来调试的时间太仓促了，没有保留别的成品演示😭
